=== Popeye985/XML-oefn/src/oef1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           xmlns="http://www.betavzw.org"
           targetNamespace="http://www.betavzw.org">
    <xs:element name="lokaal">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="pc" maxOccurs="10">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="cursist" type="xs:string" minOccurs="0" maxOccurs="2"/>
                        </xs:sequence>
                        <xs:attribute name="nr" type="xs:string"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Popeye985/XML-oefn/src/oef1.xml
<?xml version="1.0" encoding="UTF-8" ?>
<lokaal xmlns="http://www.betavzw.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.betavzw.org oef1.xsd">
    <pc nr="1">
        <cursist>Jos</cursist>
        <cursist>Marie</cursist>
    </pc>
    <pc nr="2">
        <cursist>Louis</cursist>
        <cursist>Jefke</cursist>
    </pc>
    <pc nr="3">
        <cursist>Ming Yoo Lee</cursist>
    </pc>
    <pc nr="4">
    </pc>
    <pc nr="5">
        <cursist>Jean-Marie</cursist>
        <cursist>Jean-Luc</cursist>
    </pc>
</lokaal>
